// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATXJ85Hlr9AIRz1kmLpzn3tnccCH1QOFk',
    appId: '1:530055740748:web:5bed0bd61b64e10b1be3e9',
    messagingSenderId: '530055740748',
    projectId: 'ptit-fire',
    authDomain: 'ptit-fire.firebaseapp.com',
    databaseURL: 'https://ptit-fire-default-rtdb.firebaseio.com',
    storageBucket: 'ptit-fire.appspot.com',
    measurementId: 'G-7CY9PXRD2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYaOuFZfReKdj5KVrLdjacJZx2XttaG6c',
    appId: '1:530055740748:android:68843ef802956db51be3e9',
    messagingSenderId: '530055740748',
    projectId: 'ptit-fire',
    databaseURL: 'https://ptit-fire-default-rtdb.firebaseio.com',
    storageBucket: 'ptit-fire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwu-F-VRlrxoAUJtE4LAYksSNKO1cuT7A',
    appId: '1:530055740748:ios:e85a441ef28714b21be3e9',
    messagingSenderId: '530055740748',
    projectId: 'ptit-fire',
    databaseURL: 'https://ptit-fire-default-rtdb.firebaseio.com',
    storageBucket: 'ptit-fire.appspot.com',
    iosBundleId: 'com.example.ptit',
  );
}
